Update index.html
circuitpython/web-editor pull request #17
Opened 2022-07-29 23:11 UTC by sctv

when I click on the about://flags/#enable-web-bluetooth-new-permissions-backend link on https://code.circuitpython.org/ on windows10 chrome, it loads about:blank#blocked
chrome://flags/#enable-web-bluetooth-new-permissions-backend might be a better link.

2022-07-30 03:07 UTC, makermelissa commented
This was changed in #9 so it would work on Microsoft Edge Browsers too. Copying/Pasting into the URL works with the way it is now. If we detected chrome vs edge and displayed the appropriate url, I'd be ok with that.

2022-08-04 18:39 UTC, makermelissa requested changes
Please see previous comment. This change breaks compatibility with Microsoft Edge Browsers.

2022-08-06 01:17 UTC, sctv commented
Thanks for the information, will consider it closed as I don't [currently] have the knowledge to code to detect which browser the page is being displayed on.

A work-around/stopgap might be to suggest that the user cuts and pastes the URL in chrome, as it might be mysterious otherwise.

2022-08-06 01:17 UTC, closed without merging

2022-08-06 03:22 UTC, makermelissa commented
Ok, well I'm currently working on a huge update to implement web workflow and if it seems easy enough, I might just make that part of the update.

2022-08-06 03:27 UTC, makermelissa commented
I just tested by updating with chrome:// links and they don't do anything when clicked and if you open them in a new tab, it has the same blocked issue.

2022-08-06 09:33 UTC, sctv commented
Thanks... there is probably more to linking to settings from pages in chrome. 
Cut and paste seems to be the way to do it currently. 
Sorry for taking up your time.

2022-08-06 21:12 UTC, makermelissa commented
No worries. :)