Added `hover` effect
circuitpython/web-editor pull request #33
Opened 2022-10-19 22:09 UTC by Franqsanz

Added the `hover` effect and a scss variable.

2022-10-19 23:20 UTC, makermelissa requested changes
You should be able to just add a hover to the button class and use the sass darken function instead of creating another variable.

2022-10-19 23:20 UTC, makermelissa commented on assets/sass/base/_base.scss
>      }
```suggestion
    &:hover {
        background-color: darken($purple, 15%);
    }
}
```

2022-10-19 23:25 UTC, Franqsanz commented on assets/sass/base/_base.scss
>      }
You're right! I fix it now.

2022-10-20 15:08 UTC, makermelissa approved these changes
Bracing got a bit messed up, but I fixed it. Thank you for this.

2022-10-20 15:08 UTC, merged

2022-10-20 15:22 UTC, makermelissa commented
No worries. That's how we learn. It's great to have other contributing.

2022-10-20 16:43 UTC, Franqsanz commented
Thank you very much!